#!/bin/bash

TELEGRAM_BOT_TOKEN="xxxxxxxxxxx"
TELEGRAM_CHAT_ID="-xxxxxxx"
LOG_FILE="/var/log/auth.log"
LOGGED_HOST="$(hostname -f)"
TIME="$(date)"
tail -n  0 -F $LOG_FILE | while read -r line
do
    # Kiểm tra nếu dòng log chứa thông tin truy cập SSH thành công
    if echo "$line" | grep -q "Accepted password"; then
        # Trích xuất ip từ dòng log
        ip=$(echo "$line" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
        # Gửi tin nhắn cảnh báo truy cập SSH thành công qua Telegram
        SUCCESS_MESSAGE="$(echo -e "Có đăng nhập ssh\nHost: \nFrom IP: $IP $LOGGED_HOST\nTime: $TIME") "
        curl --silent --output /dev/null -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d "chat_id=$TELEGRAM_CHAT_ID" -d "text= $SUCCESS_MESSAGE"    
    fi
    
    # Kiểm tra nếu dòng log chứa thông tin truy cập SSH không thành công
    if echo "$line" | grep -q "Failed password"; then
        # Trích xuất ip từ dòng log
        ip=$(echo "$line" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
        # Gửi tin nhắn cảnh báo truy cập SSH không thành công qua Telegram
        FAILED_MESSAGE="$(echo -e "Có kẻ đột nhập SSH không thành công:\nFrom IP: $IP\nTime: $TIME") "
        curl --silent --output /dev/null -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d "chat_id=$TELEGRAM_CHAT_ID" -d "text= $FAILED_MESSAGE"    
    fi
done
